// // app/layout.tsx
// import type { Metadata } from "next";
// import { Commissioner } from "next/font/google";
// import "./globals.css";
// import Header from "../components/Header/Header";
// import BodyWrapper from "@/components/bodywrapper/BodyWrapper";
// import AOSInit from '@/components/AOSInit/AOSInit';
// import "aos/dist/aos.css";

// const CommissionertSans = Commissioner({
//   variable: "--font-Commissioner-sans",
//   subsets: ["latin"],
// });


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const fonts = `${CommissionertSans.variable}`;

//   return (
//     <html lang="en">
//       <BodyWrapper fontClass={fonts}>
//         <Header />
//         <AOSInit />
//         {children}
//       </BodyWrapper>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Commissioner } from "next/font/google";
import "./globals.css";
import Header from "../components/Header/Header";
import BodyWrapper from "@/components/bodywrapper/BodyWrapper";
import AOSInit from '@/components/AOSInit/AOSInit';

const CommissionertSans = Commissioner({
  variable: "--font-Commissioner-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next.js App",
  description: "Fullpage + AOS Example",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const fonts = `${CommissionertSans.variable}`;

  return (
    <html lang="en">
      <BodyWrapper fontClass={fonts}>
        <Header />
        <AOSInit />
        {children}
      </BodyWrapper>
    </html>
  );
}
